export PY_DIR=/Library/Frameworks/Python.framework/Versions/3.15/bin
export PATH=$PY_DIR:$PATH
export PATH=`python3 -m site --user-base`/bin:$PATH
TMP_DIR=`realpath /tmp`
export ROOT_DIR=$TMP_DIR/$CI_PIPELINE_ID
export CCACHE_BASEDIR=$ROOT_DIR
export SRC_DIR=$ROOT_DIR/src
export BUILD_DIR=$ROOT_DIR/build
export CMAKE_INSTALL_PREFIX=$ROOT_DIR/install/Netgen.app
export PYTHONPATH=$CMAKE_INSTALL_PREFIX/Contents/Resources/`python3 -c "import os.path, sysconfig;print(os.path.relpath(sysconfig.get_path('platlib'), sysconfig.get_path('data')))"`:.
export PATH=$CMAKE_INSTALL_PREFIX/Contents/MacOS:$PATH
export MACOSX_DEPLOYMENT_TARGET=10.15
