export PY_DIR=/Library/Frameworks/Python.framework/Versions/3.14/bin
export PATH=$PY_DIR:$PATH
TMP_DIR=`realpath /tmp`
export ROOT_DIR=$TMP_DIR/$CI_PIPELINE_ID
export CCACHE_BASEDIR=$ROOT_DIR
export SRC_DIR=$ROOT_DIR/src
export BUILD_DIR=$ROOT_DIR/build
export CMAKE_INSTALL_PREFIX=$ROOT_DIR/install/Netgen.app
export PYTHONPATH=$CMAKE_INSTALL_PREFIX/Contents/Resources/`python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib(1,0,''))"`:.
export PATH=$CMAKE_INSTALL_PREFIX/Contents/MacOS:$PATH
export MACOSX_DEPLOYMENT_TARGET=10.15
