set icon_data {
/* XPM */
static char *icon2[] = {
/* width height num_colors chars_per_pixel */
"   60    60        6            1",
/* colors */
". c #000000",
"# c #008000",
"a c #00b700",
"b c #00c700",
"c c #00ff00",
"d s c None c None",
/* pixels */
"dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
"dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
"dddddddddddddddd..........dddddddddddddddddddddddddddddddddd",
"ddddddddddddddd.c..cc#####................dddddddddddddddddd",
"ddddddddddddd..cccc..ccccccccccccccccc...#...............ddd",
"dddddddddddd.cccccccc..cccccccccccc...ccc..cccccccccc###..dd",
"ddddddddddd.ccccccccccc..ccccccccc.cccccccc.ccccccccccc...dd",
"dddddddddd.cccccccccccccc.cccccc..cccccccccc.ccccccccc.b..dd",
"ddddddddd.cccccccccccccccc..ccc.ccccccccccccc..cccccc.bb..dd",
"ddddddd........................cccccccccccccccc.cccc.bbb..dd",
"dddddd.ccc.ccccccccccccccccc..#..............ccc.c..bbbb..dd",
"dddd..ccccc..cccccccccccccc.#..##############.....bbbbb.b.dd",
"ddd.ccccccccc..ccccccccccc.##.#.#################.bbbbb.b.dd",
"dd.cccccccccccc..cccccccc.###.##.################.bbbbb.b.dd",
"d..cccccccccccccc..ccccc.####.###.###############.bbbbb.b.dd",
"d.a..............cc..cc.#####.####.##############.bbbb.bb.dd",
"d..aaaaaaaaaaaaaa......######.#####.#############.bbbb.bb.dd",
"d.a.aaaaaaaaaaaaaaaaa...#####.######..###########.bbbb.bb.dd",
"d.aa.aaaaaaaaaaaaaaaa...#####.########.##########.bbbb.bb.dd",
"d.aaa.aaaaaaaaaaaaaaa..#.####.#########.##########..b.bbb.dd",
"d.aaaa.aaaaaaaaaaaaaa..#.####.##########.#########..b.bbb.dd",
"d.aaaaa..aaaaaaaaaaaa..##.###.###########.########..b.bbb.dd",
"d.aaaaaaa.aaaaaaaaaaa..###.###.###########.#######..b.bbb.dd",
"d.aaaaaaaa.aaaaaaaaaa..###.###.############.######..b.bbb#.d",
"d.aaaaaaaaa.aaaaaaaaa..####.##.#############.#####...bbbb#.d",
"d.aaaaaaaaaa.aaaaaaaa..#####.#.##############.####...bbbb#.d",
"d.aaaaaaaaaaa.aaaaaaa..#####.#.###############.###...bbbb#.d",
"d.aaaaaaaaaaaa.aaaaaa..######..################.##...bbbb#.d",
"d.aaaaaaaaaaaaa.aaaaaaa.#####..#################.#..bbbbb#.d",
"d.aaaaaaaaaaaaaa.aaaaaa.#####.............#######...bbbbb#.d",
"d.aaaaaaaaaaaaaaa.aaaaa.####.###.#########..........bbbbbb.d",
"dd.aaaaaaaaaaaaaaa.aaaa.###.#####..##############...bbbbbb.d",
"dd.aaaaaaaaaaaaaaaa.aaa.##.########.############.b...bbbbb.d",
"dd.aaaaaaaaaaaaaaaaa.aa.#.##########...########.b.bbb.bbbb.d",
"dd.aaaaaaaaaaaaaaaaaa....##############.######.bb.bbb.bbbb.d",
"dd.aaaaaaaaaaaaaaaaaaaa...##############..###.bbb.bbbb.bbb.d",
"dd.aaaaaaaaaaaaaaaaaa..a.a..............##.#.bbbb.bbbb.bbb.d",
"dd.aaaaaaaaaaaaaaaaa.aaaa.aaaaaaaaaaaaaa....bbbb.bbbbbb.bb.d",
"dd.aaaaaaaaaaaaaaaa.aaaaa.aaaaaaaaaaaaaaaaa.bbbb.bbbbbbb.b.d",
"dd.aaaaaaaaaaaaaaa.aaaaaaa.aaaaaaaaaaaaaaaa.bbbb.bbbbbbb.b.d",
"dd.aaaaaaaaaaaaaa.aaaaaaaaa.aaaaaaaaaaaaaaa.bbbb.bbbbbbbb..d",
"dd.aaaaaaaaaaaaa.aaaaaaaaaaa.aaaaaaaaaaaaaa.bbb.bbbbbbbbb..d",
"dd.aaaaaaaaaaaa.aaaaaaaaaaaaa.aaaaaaaaaaaaa.bbb.bbbbbbbbbb.d",
"dd.aaaaaaaaaaa.aaaaaaaaaaaaaaa.aaaaaaaaaaaa.bbb.bbbbbbbbbb.d",
"dd.aaaaaaaaaa.aaaaaaaaaaaaaaaaa.aaaaaaaaaaaa.bb.bbbbbbbbb.dd",
"dd.aaaaaaaaa.aaaaaaaaaaaaaaaaaaa.aaaaaaaaaaa.bb.bbbbbbbb.ddd",
"dd.aaaaaaaa.aaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaa.b.bbbbbbbb.dddd",
"dd.aaaaaaa.aaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaa.b.bbbbbbb.ddddd",
"dd.aaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaa.b.bbbbbb.dddddd",
"dd.aaaa..aaaaaaaaaaaaaaaaaaaaaaaaaaa..aaaaaa.b.bbbbb.ddddddd",
"ddd.aa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaa..bbbb..dddddddd",
"ddd.a.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaa..bbb.dddddddddd",
"ddd..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaa..bb.ddddddddddd",
"ddd........aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aa..b.dddddddddddd",
"ddddddddddd.............aaaaaaaaaaaaaaaaaa.a...ddddddddddddd",
"dddddddddddddddddddddddd............aaaaaaa...dddddddddddddd",
"dddddddddddddddddddddddddddddddddddd.........ddddddddddddddd",
"dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
"dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
"dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
};
}
